// This source code is a part of Project Violet.
// Copyright (C) 2020. rollrat. Licensed under the MIT License.

import 'package:communitydownloader/settings/settings.dart';
import 'package:expandable/expandable.dart';
import 'package:flutter/material.dart';

const supportSites = [
  'a*c',
  'a*cnews',
  'a*cotvs',
  'a*ademicearth',
  'a*ast',
  'a*n',
  'a*obeconnect',
  'a*obepass',
  'a*obetv',
  'a*ultswim',
  'a*networks',
  'a*reecatv',
  'a*rmozilla',
  'a*iexpress',
  'a*jazeera',
  'a*locine',
  'a*phap**no',
  'a*cnetworks',
  'a*ericastestkitchen',
  'a*p',
  'a*imeondemand',
  'a*vato',
  'a*l',
  'a*a',
  'a*arat',
  'a*pleconnect',
  'a*pletrailers',
  'a*chiveorg',
  'a*d',
  'a*kena',
  'a*te',
  'a*iancrush',
  'a*resplayer',
  'a*ttechchannel',
  'a*vat',
  'a*dimedia',
  'a*dioboom',
  'a*diomack',
  'a*aan',
  'a*s',
  'a*medien',
  'b*idu',
  'b*ndcamp',
  'b*c',
  'b*ampro',
  'b*atport',
  'b*eg',
  'b*hindkink',
  'b*llmedia',
  'b*t',
  'b*i',
  'b*gflix',
  'b*ld',
  'b*libili',
  'b*obiochiletv',
  'b*qle',
  'b*tchute',
  'b*eacherreport',
  'b*inkx',
  'b*oomberg',
  'b*kecc',
  'b*stonglobe',
  'b*b',
  'b*',
  'b*avotv',
  'b*eakcom',
  'b*ightcove',
  'b*sinessinsider',
  'b*zzfeed',
  'b*utv',
  'c*6',
  'c*mdemy',
  'c*mmodels',
  'c*mtube',
  'c*mwithher',
  'c*nalc2',
  'c*nalplus',
  'c*nvas',
  'c*rambatv',
  'c*rtoonnetwork',
  'c*c',
  'c*s',
  'c*sinteractive',
  'c*slocal',
  'c*snews',
  'c*ssports',
  'c*c',
  'c*ma',
  'c*tv',
  'c*a',
  'c*skatelevize',
  'c*annel9',
  'c*arlierose',
  'c*aturbate',
  'c*illoutzone',
  'c*irbit',
  'c*nchcast',
  'c*nemax',
  'c*scolive',
  'c*sw',
  'c*iphunter',
  'c*ippit',
  'c*iprs',
  'c*ipsyndicate',
  'c*osertotruth',
  'c*oudflarestream',
  'c*oudy',
  'c*ubic',
  'c*yp',
  'c*t',
  'c*bc',
  'c*n',
  'c*medycentral',
  'c*mmon',
  'c*mmonmistakes',
  'c*mmonprotocols',
  'c*ndenast',
  'c*ntv',
  'c*rus',
  'c*ub',
  'c*acked',
  'c*ackle',
  'c*ooksandliars',
  'c*unchyroll',
  'c*pan',
  'c*snews',
  'c*vnews',
  'c*ltureunplugged',
  'c*riositystream',
  'c*tv',
  'd*ilymail',
  'd*ilymotion',
  'd*um',
  'd*tv',
  'd*tp',
  'd*ezer',
  'd*fense',
  'd*mocracynow',
  'd*b',
  'd*m',
  'd*gg',
  'd*giteka',
  'd*scovery',
  'd*scoverygo',
  'd*scoverynetworks',
  'd*scoveryvr',
  'd*sney',
  'd*speak',
  'd*ive',
  'd*tsub',
  'd*uyutv',
  'd*lay',
  'd*bonanza',
  'd*eisat',
  'd*opbox',
  'd*tuber',
  'd*tv',
  'd*ube',
  'd*mpert',
  'd*tv',
  'd*',
  'e*gleplatform',
  'e*aumsworld',
  'e*homsk',
  'e*ghead',
  'e*ow',
  'e*ghttracks',
  'e*nthusan',
  'e*tb',
  'e*lentube',
  'e*pais',
  'e*bedly',
  'e*gadget',
  'e*orner',
  'e*oprofile',
  'e*capist',
  'e*pn',
  'e*ri',
  'e*ropa',
  'e*eryonesmixtape',
  'e*potv',
  'e*pressen',
  'e*tractors',
  'e*tremetube',
  'e*edotv',
  'f*cebook',
  'f*z',
  'f*2',
  'f*zenit',
  'f*lmon',
  'f*lmweb',
  'f*rsttv',
  'f*vemin',
  'f*vetv',
  'f*ickr',
  'f*lketinget',
  'f*otyroom',
  'f*rmula1',
  'f*urtube',
  'f*x',
  'f*x9',
  'f*xgay',
  'f*xnews',
  'f*xsports',
  'f*anceculture',
  'f*anceinter',
  'f*ancetv',
  'f*eesound',
  'f*eespeech',
  'f*eshlive',
  'f*ontendmasters',
  'f*nimation',
  'f*nk',
  'f*sion',
  'f*networks',
  'g*ia',
  'g*meinformer',
  'g*mespot',
  'g*mestar',
  'g*skrank',
  'g*zeta',
  'g*cvault',
  'g*neric',
  'g*ycat',
  'g*antbomb',
  'g*ga',
  'g*gya',
  'g*ide',
  'g*obo',
  'g*',
  'g*dtube',
  'g*lem',
  'g*ogledrive',
  'g*ogleplus',
  'g*oglesearch',
  'g*shgay',
  'g*utechconf',
  'g*oupon',
  'h*o',
  'h*arthisat',
  'h*ise',
  'h*llp**no',
  'h*lsinki',
  'h*ntaistigma',
  'h*tv',
  'h*dive',
  'h*storicfilms',
  'h*tbox',
  'h*trecord',
  'h*etv',
  'h*rnbunny',
  'h*tnewhiphop',
  'h*tstar',
  'h*wcast',
  'h*wstuffworks',
  'h*ti',
  'h*ajiao',
  'h*ffpost',
  'h*ngama',
  'h*pem',
  'i*n',
  'i*db',
  'i*ggaming',
  'i*gur',
  'i*a',
  'i*c',
  'i*davideo',
  'i*foq',
  'i*stagram',
  'i*ternazionale',
  'i*ternetvideoarchive',
  'i*rima',
  'i*iyi',
  'i*90tv',
  'i*v',
  'i*i',
  'i*ideon',
  'i*ara',
  'i*lesene',
  'j*mendo',
  'j*uxvideo',
  'j*j',
  'j*ve',
  'j*platform',
  'k*kao',
  'k*ltura',
  'k*nalplay',
  'k*nkan',
  'k*raoketv',
  'k*rrierevideos',
  'k*ezmovies',
  'k*tnet',
  'k*anacademy',
  'k*ckstarter',
  'k*nja',
  'k*nopoisk',
  'k*nserthusetplay',
  'k*asview',
  'k*6',
  'k*si',
  'k*wo',
  'l*7',
  'l*ola1tv',
  'l*i',
  'l*p',
  'l*cture2go',
  'l*cturio',
  'l*eco',
  'l*go',
  'l*monde',
  'l*nta',
  'l*braryofcongress',
  'l*bsyn',
  'l*fenews',
  'l*melight',
  'l*ne',
  'l*nkedin',
  'l*nuxacademy',
  'l*tv',
  'l*vejournal',
  'l*veleak',
  'l*vestream',
  'l*kgo',
  'l*calnews8',
  'l*vehomep**n',
  'l*t',
  'l*nda',
  'm*',
  'm*ilru',
  'm*lltv',
  'm*ngomolo',
  'm*nyvids',
  'm*rkiza',
  'm*ssengeschmacktv',
  'm*tchtv',
  'm*r',
  'm*dialaan',
  'm*diaset',
  'm*diasite',
  'm*dici',
  'm*gaphone',
  'm*ipai',
  'm*lonvod',
  'm*ta',
  'm*tacafe',
  'm*tacritic',
  'm*oon',
  'm*tv',
  'm*aopai',
  'm*crosoftvirtualacademy',
  'm*nistrygrid',
  'm*noto',
  'm*omio',
  'm*t',
  'm*tele',
  'm*xcloud',
  'm*b',
  'm*et',
  'm*evideo',
  'm*fos*x',
  'm*jvideo',
  'm*rningstar',
  'm*therless',
  'm*torsport',
  'm*vieclips',
  'm*viezine',
  'm*vingimage',
  'm*n',
  'm*v',
  'm*enchentv',
  'm*ave',
  'm*channels',
  'm*space',
  'm*spass',
  'm*vi',
  'm*vidster',
  'n*tionalgeographic',
  'n*ver',
  'n*a',
  'n*c',
  'n*r',
  'n*tv',
  'n*rdcubed',
  'n*teasemusic',
  'n*tzkino',
  'n*wgrounds',
  'n*wstube',
  'n*xtmedia',
  'n*xx',
  'n*l',
  'n*k',
  'n*l',
  'n*ck',
  'n*conico',
  'n*necninemedia',
  'n*negag',
  'n*nenow',
  'n*ntendo',
  'n*pwworld',
  'n*belprize',
  'n*co',
  'n*nktube',
  'n*ovo',
  'n*rmalboots',
  'n*svideo',
  'n*va',
  'n*wness',
  'n*z',
  'n*o',
  'n*r',
  'n*k',
  'n*l',
  'n*vcojp',
  'n*vde',
  'n*vru',
  'n*evo',
  'n*vid',
  'n*times',
  'n*z',
  'o*atv',
  'o*noklassniki',
  'o*toberfesttv',
  'o*ce',
  'o*demandkorea',
  'o*et',
  'o*ionstudios',
  'o*yala',
  'o*enload',
  'o*a',
  'o*f',
  'o*tsidetv',
  'p*cktpub',
  'p*ndoratv',
  'p*rliamentliveuk',
  'p*treon',
  'p*s',
  'p*arvideo',
  'p*ertube',
  'p*ople',
  'p*rformgroup',
  'p*riscope',
  'p*ilharmoniedeparis',
  'p*oenix',
  'p*otobucket',
  'p*carto',
  'p*ksel',
  'p*nkbike',
  'p*adform',
  'p*atzi',
  'p*ayfm',
  'p*ayplustv',
  'p*ays',
  'p*aytvak',
  'p*ayvid',
  'p*aywire',
  'p*uralsight',
  'p*domatic',
  'p*kemon',
  'p*lskieradio',
  'p*pcorntimes',
  'p*pcorntv',
  'p*rn91',
  'p*rncom',
  'p*rnhd',
  'p*rnhub',
  'p*rnotube',
  'p*rnovoisines',
  'p*rnoxo',
  'p*esstv',
  'p*osiebensat1',
  'p*hutv',
  'p*ls4',
  'p*video',
  'q*music',
  'r*',
  'r*diobremen',
  'r*diocanada',
  'r*diode',
  'r*diofrance',
  'r*diojavan',
  'r*i',
  'r*ywenderlich',
  'r*maradio',
  'r*s',
  'r*dbulltv',
  'r*ddit',
  'r*dtube',
  'r*giotv',
  'r*ntv',
  'r*study',
  'r*uters',
  'r*verbnation',
  'r*ce',
  'r*cdecouverte',
  'r*220',
  'r*ckstargames',
  'r*osterteeth',
  'r*ttentomatoes',
  'r*xwel',
  'r*zhlas',
  'r*bf',
  'r*e',
  'r*l2',
  'r*lnl',
  'r*p',
  'r*s',
  'r*ve',
  'r*vnh',
  'r*vs',
  'r*hd',
  'r*tube',
  'r*tv',
  'r*utu',
  'r*v',
  's*fari',
  's*po',
  's*vefrom',
  's*s',
  's*reencast',
  's*reencastomatic',
  's*rippsnetworks',
  's*te',
  's*eker',
  's*nateisvp',
  's*ndtonews',
  's*rvus',
  's*venplus',
  's*xu',
  's*znamzpravy',
  's*ahid',
  's*ared',
  's*owroomlive',
  's*na',
  's*xplay',
  's*y',
  's*ylinewebcams',
  's*ynewsarabia',
  's*ideshare',
  's*ideslive',
  's*utload',
  's*otri',
  's*otr',
  's*hu',
  's*nyliv',
  's*undcloud',
  's*undgasm',
  's*uthpark',
  's*ankbang',
  's*ankwire',
  's*iegel',
  's*iegeltv',
  's*ike',
  's*ort5',
  's*ortbox',
  's*ortdeutschland',
  's*ringboardplatform',
  's*rout',
  's*gssr',
  's*mediathek',
  's*anfordoc',
  's*eam',
  's*itcher',
  's*reamable',
  's*reamcloud',
  's*reamcz',
  's*reetvoice',
  's*retchinternet',
  's*v',
  's*np**no',
  's*erigesradio',
  's*t',
  's*rmediathek',
  's*fy',
  's*tvhu',
  't*gesschau',
  't*ss',
  't*stytrade',
  't*s',
  't*slifeway',
  't*achable',
  't*achertube',
  't*achingchannel',
  't*amcoco',
  't*amtreehouse',
  't*chtalks',
  't*d',
  't*le13',
  't*le5',
  't*lebruxelles',
  't*lecinco',
  't*legraaf',
  't*lemb',
  't*lequebec',
  't*letask',
  't*lewebion',
  't*nnistv',
  't*nplay',
  't*sturl',
  't*1',
  't*o',
  't*eintercept',
  't*eplatform',
  't*escene',
  't*estar',
  't*esun',
  't*eweatherchannel',
  't*isamericanlife',
  't*isav',
  't*isoldhouse',
  't*reeqsdn',
  't*ktok',
  't*nypic',
  't*z',
  't*aflix',
  't*ggle',
  't*nline',
  't*ongoggles',
  't*utv',
  't*ypics',
  't*aileraddict',
  't*ilulilu',
  't*unews',
  't*utv',
  't*be8',
  't*bitv',
  't*dou',
  't*mblr',
  't*nein',
  't*nepk',
  't*rbo',
  't*rner',
  't*2',
  't*2dk',
  't*2hu',
  't*4',
  't*5mondeplus',
  't*a',
  't*anouvelles',
  't*c',
  't*igle',
  't*land',
  't*n24',
  't*net',
  't*noe',
  't*now',
  't*p',
  't*play',
  't*player',
  't*eakers',
  't*entyfourvideo',
  't*entymin',
  't*entythreevideo',
  't*itcasting',
  't*itch',
  't*itter',
  'u*emy',
  'u*n',
  'u*ctv',
  'u*tvplay',
  'u*g',
  'u*istra',
  'u*ity',
  'u*l',
  'u*lynk',
  'u*ort',
  'u*play',
  'u*anetwork',
  'u*atoday',
  'u*tream',
  'u*tudio',
  'v*rzesh3',
  'v*ox7',
  'v*ehd',
  'v*oh',
  'v*sti',
  'v*vo',
  'v*tv',
  'v*1',
  'v*ce',
  'v*dbit',
  'v*ddler',
  'v*dea',
  'v*deodetective',
  'v*deofyme',
  'v*deomore',
  'v*deopress',
  'v*dio',
  'v*dlii',
  'v*dme',
  'v*dzi',
  'v*er',
  'v*ewlift',
  'v*idea',
  'v*ki',
  'v*meo',
  'v*mple',
  'v*ne',
  'v*qeo',
  'v*u',
  'v*',
  'v*ive',
  'v*dlocker',
  'v*dpl',
  'v*dplatform',
  'v*icerepublic',
  'v*ot',
  'v*xmedia',
  'v*ak',
  'v*t',
  'v*v',
  'v*hare',
  'v*be',
  'v*clip',
  'v*vvid',
  'v*borymos',
  'v*aar',
  'w*kanim',
  'w*lla',
  'w*shingtonpost',
  'w*t',
  'w*tchbox',
  'w*tchindianp**n',
  'w*r',
  'w*bcaster',
  'w*bofstories',
  'w*ibo',
  'w*iqitv',
  'w*stia',
  'w*rldstarhiphop',
  'w*j',
  'w*e',
  'x*ef',
  'x*oxclips',
  'x*ileshare',
  'x*amster',
  'x*ami',
  'x*malaya',
  'x*inus',
  'x*xx',
  'x*tream',
  'x*ube',
  'x*ite',
  'x*ideos',
  'x*xymovies',
  'y*hoo',
  'y*ndexdisk',
  'y*ndexmusic',
  'y*ndexvideo',
  'y*pfiles',
  'y*sjapan',
  'y*nyuetai',
  'y*et',
  'y*ujizz',
  'y*uku',
  'y*unow',
  'y*up**n',
  'y*urp**n',
  'y*urupload',
  // 'y*utube',
  'z*piks',
  'z*q1',
  'z*ttoo',
  'z*f',
  'z*ngmp3',
  'z*pe',

  //
  //  Violet App Supports
  //
  'h*tomi',
  'e*entai',
  'e*hentai',
  'arca.live',
  'dcinside',
  'gelbooru',
  'instagram',
  'inven',
  'iroriapp',
  'pixiv',
  'ruliweb',
  'twitter',
];

class SupportPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var cc = List<String>.from(supportSites);
    cc.sort();
    var mm = cc.join(', ');
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.lime,
        title: Text('SUPPORTS'),
      ),
      body: SingleChildScrollView(
        physics: BouncingScrollPhysics(),
        child: Column(
          children: [
            ExpandableNotifier(
              child: Padding(
                padding: EdgeInsets.symmetric(vertical: 4.0),
                child: ScrollOnExpand(
                  child: ExpandablePanel(
                    theme: ExpandableThemeData(
                        iconColor:
                            Settings.themeWhat ? Colors.white : Colors.grey,
                        animationDuration: const Duration(milliseconds: 500)),
                    header: Padding(
                      padding: EdgeInsets.fromLTRB(12, 12, 0, 0),
                      child: Text('소개'),
                    ),
                    expanded: Padding(
                      padding: EdgeInsets.fromLTRB(16, 4, 16, 4),
                      child: Column(
                        children: [
                          Text(
                              'Violet Community Downloader는 수 많은 개별 웹 페이지 및 커뮤니티, 동영상 제공 웹 사이트,'
                                      ' 스트리밍 사이트, 블로그, 만화 제공사이트, 소셜 미디어 웹 사이트, 이미지 호스팅 사이트들의 다운로더를 제공하고 있습니다. ' +
                                  ' 어떤 웹사이트들은 각 국가의 검열 정책에 따라 다운로드가 불가능할 수 있습니다.',
                              style: TextStyle(fontSize: 12)),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Container(
              width: double.infinity,
              height: 0.5,
              color: Settings.themeWhat
                  ? Colors.grey.shade600
                  : Colors.grey.shade400,
            ),
            ExpandableNotifier(
              child: Padding(
                padding: EdgeInsets.symmetric(vertical: 4.0),
                child: ScrollOnExpand(
                  child: ExpandablePanel(
                    theme: ExpandableThemeData(
                        iconColor:
                            Settings.themeWhat ? Colors.white : Colors.grey,
                        animationDuration: const Duration(milliseconds: 500)),
                    header: Padding(
                      padding: EdgeInsets.fromLTRB(12, 12, 0, 0),
                      child: Text('모든 추출기 정보'),
                    ),
                    expanded: Padding(
                      padding: EdgeInsets.fromLTRB(16, 4, 16, 4),
                      child: Column(
                        children: [
                          Text(mm, style: TextStyle(fontSize: 12)),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Container(
              width: double.infinity,
              height: 0.5,
              color: Settings.themeWhat
                  ? Colors.grey.shade600
                  : Colors.grey.shade400,
            ),
            ExpandableNotifier(
              child: Padding(
                padding: EdgeInsets.symmetric(vertical: 4.0),
                child: ScrollOnExpand(
                  child: ExpandablePanel(
                    theme: ExpandableThemeData(
                        iconColor:
                            Settings.themeWhat ? Colors.white : Colors.grey,
                        animationDuration: const Duration(milliseconds: 500)),
                    header: Padding(
                      padding: EdgeInsets.fromLTRB(12, 12, 0, 0),
                      child: Text('다운로더 지원 요청하기'),
                    ),
                    expanded: Padding(
                      padding: EdgeInsets.fromLTRB(16, 4, 16, 4),
                      child: Column(
                        children: [
                          Text(
                              '새로운 웹사이트의 다운로더를 원하거나, 다운로드 실패문제, 앱 문제에 관한 모든 사항들은 violet.dev.master@gmail.com 또는 플레이스토어에 지원을 요청하세요.'
                              ' 다운로드 실패문제의 경우엔 다운로더 요청 URL과 작업의 경우엔 작업정보까지 모두 함께 알려주셔야합니다.',
                              style: TextStyle(fontSize: 12)),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
            // Container(
            //   width: double.infinity,
            //   height: 0.5,
            //   color: Settings.themeWhat
            //       ? Colors.grey.shade600
            //       : Colors.grey.shade400,
            // ),
          ],
        ),
      ),
    );
  }
}
